### ISSUE TITLE
Plugin hangs on loading file

### ISSUE THREAD

**Issue by Synthetica9** [idris-hackers/atom-language-idris#202] opened 2018-02-23 13:38 UTC
Whenever I try to load a file (<kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>r</kbd>, `language-idris:typecheck`), all it does is display `Idris: Typechecking...` forever. The Idris compiler does get launched, I can tell from htop, but it does not produce any (significant) cpu usage.

I am on NixOS.

```
$ atom --version         
Atom    : 1.23.3                                      
Electron: 1.6.15                                      
Chrome  : 56.0.2924.87                                
Node    : 7.4.0                                       
$ nix-info -m            
 - system: `"x86_64-linux"`                           
 - host os: `Linux 4.15.3, NixOS, 18.03pre127921.9b25b9347d9 (Impala)`                                      
 - multi-user?: `yes`                                 
 - sandbox: `yes`                                     
 - version: `nix-env (Nix) 1.11.16`                   
 - channels(root): `"nixos-18.03pre127921.9b25b9347d9"`                                                     
 - channels(synthetica): `"nixos-18.03pre119110.2ddcdcce26"`                                                
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by justjoheinz** [comment] 2018-02-23 14:12
How does idris behave when you typecheck the file without Atom? Depending on the code it is behaviour which might occur since idris is simply busy type checking. 

Can you share the code you attempt to typecheck?

**Comment by Synthetica9** [comment] 2018-02-23 14:14
It is the case for any code, really. Even for simple examples like:

```
module Test

test : Nat
test = 5
```

**Comment by justjoheinz** [comment] 2018-02-23 14:30
Hmm, took about a second on my installation? Do you happen to have an `.ipkg` file lying around in the same directory? What does the Chrome developer console say (Cmd+Opt+I on a Mac)?

**Comment by Synthetica9** [comment] 2018-02-23 14:40
Hmm, when I try it from a different directory it does work. Indeed, when I have an `.ipkg` (`contrib`) file it doesn't work. Why is this, is it trying to build the whole package first? How can I work around this?

**Comment by justjoheinz** [comment] 2018-02-23 15:05
`contrib` as in `Idris-dev/libs/contrib/` ? Yes it will try to compile everything which can take awhile. You can work around it by renaming the extension of the ipkg file, though I have not tried that myself.

I close the issue, because that seems to be intended behavior. If you have suggestions or disagree, please feel free to open another issue.

**Closed by justjoheinz** 2018-02-23 15:05 UTC
