### ISSUE TITLE
Error on startup: Uncaught TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by david-christiansen** [idris-hackers/atom-language-idris#23] opened 2015-06-04 11:49 UTC
When I start Atom with an Idris file open, I get the following error:
```
Uncaught TypeError: Cannot read property 'stdin' of undefined
/home/davidc/.atom/packages/language-idris/lib/idris-model.coffee:105
Hide Stack Trace
TypeError: Cannot read property 'stdin' of undefined
  at IdrisModel.sendCommand (/home/davidc/.atom/packages/language-idris/lib/idris-model.coffee:105:13)
  at IdrisModel.prepareCommand (/home/davidc/.atom/packages/language-idris/lib/idris-model.coffee:111:6)
  at IdrisModel.load (/home/davidc/.atom/packages/language-idris/lib/idris-model.coffee:114:6)
  at IdrisController.loadFile (/home/davidc/.atom/packages/language-idris/lib/idris-controller.coffee:100:12)
  at IdrisController.paneChanged (/home/davidc/.atom/packages/language-idris/lib/idris-controller.coffee:82:10)
  at /home/davidc/.atom/packages/language-idris/lib/idris-controller.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:298:21)
  at tabs-tab.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:159:24)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

This is on Ubuntu 15.04 running the latest Atom and the latest `language-idris` release from the settings window.

**Comment by archaeron** [comment] 2015-06-04 11:52
thx, I'll look into it :)

**Comment by david-christiansen** [comment] 2015-06-04 11:53
I'll keep the reports coming :-)  The only other package that I installed was `hidpi`, because the Linux version of Atom doesn't have native HiDPI support for some reason and my XPS 13 has absurdly many pixels.

**Comment by archaeron** [comment] 2015-06-04 11:58
please do :)
but I'll only be able to look at them in the evening, sorry. need to work :)

and congrats on the pixels :D

**Comment by archaeron** [comment] 2015-06-04 19:28
this is interesting.

did you set the path to idris in the config or do you have it in the path?
looks as if it couldn't find the idris compiler (not that that is an excuse for crashing :D)

**Comment by archaeron** [comment] 2015-06-04 19:43
I just had the same error, but could not reproduce it yet.

**Comment by david-christiansen** [comment] 2015-06-04 20:32
`idris` is on my default path, but I set it in the config to be safe :) It's in its own Cabal sandbox, fwiw.

**Comment by archaeron** [comment] 2015-06-04 21:30
Should work fine in a sandbox (emphasis on should here :P).
I'll have to build the whole thing more failure proof. Maybe introduce `Either` instead of the strange `null`s. Too bad I can''t use PureScript.

**Comment by david-christiansen** [comment] 2015-06-04 22:08
What about writing it in Idris? It can generate JS...

**Comment by archaeron** [comment] 2015-06-04 22:14
:D
The Atom API feels so imperative that I'd have no idea on how to even begin doing it in either language.

**Comment by david-christiansen** [comment] 2015-06-05 17:44
Have you seen Edwin's effects library? You could package up the portion of the Atom API that you use in that lib. But it'd be a big job!

**Comment by archaeron** [comment] 2015-06-05 17:59
I just started to read his paper that got him the award. It starts really promising.

**Comment by archaeron** [comment] 2015-06-05 18:01
Not sure if it's worth the effort here.
But I'll need to find a project in Idris to really learn it eventually.

**Comment by LeifW** [comment] 2015-06-05 19:09
https://www.npmjs.com/package/adt ?
Also, Facebook's "flow" typechecker does type inference on existing JS projects, including dataflow analysis for nullity checks: http://sitr.us/talks/flow/

**Comment by archaeron** [comment] 2015-06-05 20:27
@LeifW cool. there is another one here: https://github.com/puffnfresh/daggy

I just ported everything to CoffeeScript but was asking myself if I should use TypeScript, because iof the types :P

**Comment by LeifW** [comment] 2015-06-05 21:04
CoffeeScript seems like a partial step in porting to PureScript / Idris / whatever, because the syntax is more Haskell-like.

**Comment by archaeron** [comment] 2015-06-06 00:56
The part that scares me a bit is chaning highly effectful and mutable code to a functinal API :)

**Comment by archaeron** [comment] 2015-06-06 10:56
I just realized that a large part of the code is pure anyway. only two files ( `idris-controller.coffee`,  `language-idris.coffee`) and the views are not.

how hard is it to call JS code generated from Idris?

**Comment by alexchandel** [comment] 2015-06-12 08:38
Just had the same error. My Idris path was set to `/usr/local/bin/idris`, which is indeed where my `idris` binary is.

**Comment by archaeron** [comment] 2015-07-04 18:48
I found a way of reproducing this.

when I have this program:

```idris
module Main

plusAssoc : (l, c, r : Nat) -> l `plus` (c `plus` r) = (l `plus` c) `plus` r
plusAssoc Z c r = ?plusAssoc_rhs_1
plusAssoc (S l) c r = ?plusAssoc_rhs_2
```

and then typecheck, search for the type of `S` in `(S l)` the compiler crashes and the next
command will result in "Uncaught TypeError: Cannot read property 'stdin' of null".

**Comment by alexchandel** [comment] 2015-08-03 09:24
I still get this whenever I run any command

**Comment by archaeron** [comment] 2015-08-03 16:43
@alexchandel what version of idris are you using?
did you insert a path into the settings? if yes, could you paste it here?

**Comment by alexchandel** [comment] 2015-08-05 18:22
Idris 0.9.18, the latest on Homebrew. The path is correctly set to `/usr/local/bin/idris`.

**Comment by archaeron** [comment] 2015-08-07 10:54
I've tested it now on my mac but with a self compiled version.

Idris 0.9.18.1
OS X 10.10.4
Atom 1.0.5

path set in the settings.

And it all works as it should.
So we'll need to pin the error down a bit.

I'll try installing idris from homebrew too

**Comment by archaeron** [comment] 2015-08-07 11:54
I just tried this with the newest version of idris from homebrew.
I tried it with both
`/usr/local/Cellar/idris/0.9.18/bin/idris`
and
`/usr/local/bin/idris`
it's both working for me.

**Comment by archaeron** [comment] 2015-08-08 17:50
@alexchandel I implemented error messages for when the compiler can't be found/crashes
 https://github.com/idris-hackers/atom-language-idris/commit/75e9dcaaa3c2da4e2b3a7ff8af6f54fa6b723780

could you update to the new version (v0.2.1) and tell me what error you get?

**Comment by NightRa** [comment] 2015-08-08 19:03
I've been getting the same error until the update, but now there's another error - #45 :)

**Comment by archaeron** [comment] 2015-08-09 17:29
There should be better error messages for this error now, that try to tell you what went wrong. I'm closing this issue for new ones with the new error messages.

https://github.com/idris-hackers/atom-language-idris/issues/42

**Closed by archaeron** 2015-08-09 17:29 UTC
Labels: bug
